//! Guest-entrypoint plumbing for `src/main.rs`.
//!
//! Under LEZ v0.2.0-rc4 this was generated by SPEL's `#[lez_program]` macro,
//! which no longer exists in v0.2.1.

use lee_core::{
    account::{Account, AccountWithMetadata},
    program::{AccountPostState, DEFAULT_PROGRAM_ID},
};

/// Drops `(pre, post)` pairs that the state machine would reject.
///
/// `validate_execution` rule 7 fails any post-state whose `program_owner` is
/// `DEFAULT_PROGRAM_ID` when the matching pre-state was not a default account,
/// and rule 4 forbids changing `program_owner`. That is the shape of a signer
/// identity account - here `payer` on `Initialize`, and `user_native` on the
/// paths where WLEZ only reads it - so echoing it unchanged would be fatal once
/// its nonce has been bumped by an earlier transaction.
///
/// Dropping the pair is safe: the state machine only walks the pre-states a
/// program declares, so an omitted account is excluded from the diff and left
/// untouched.
///
/// Verbatim port of the SPEL macro's filter; see the bonding-curve copy for the
/// full rationale.
#[must_use]
pub fn filter_output(
    pre_states: Vec<AccountWithMetadata>,
    post_states: Vec<AccountPostState>,
) -> (Vec<AccountWithMetadata>, Vec<AccountPostState>) {
    pre_states
        .into_iter()
        .zip(post_states)
        .filter(|(pre, post)| {
            let is_default_owner = pre.account.program_owner == DEFAULT_PROGRAM_ID;
            let pre_is_default = pre.account == Account::default();
            let has_claim = post.required_claim().is_some();
            !is_default_owner || pre_is_default || has_claim
        })
        .unzip()
}
