//! Guest-entrypoint plumbing shared by every instruction in `src/main.rs`.
//!
//! Under LEZ v0.2.0-rc4 this was generated by SPEL's `#[lez_program]` macro,
//! which no longer exists in v0.2.1.

use lee_core::{
    account::{Account, AccountWithMetadata},
    program::{AccountPostState, DEFAULT_PROGRAM_ID},
};

/// Drops `(pre, post)` pairs that the state machine would reject.
///
/// `validate_execution` rule 7 fails any post-state whose `program_owner` is
/// `DEFAULT_PROGRAM_ID` when the matching pre-state was not a default account,
/// and rule 4 forbids changing `program_owner` - exactly the shape of a signer
/// identity account (`creator` on create/pause/resume/close/withdraw) whose
/// nonce an earlier transaction has already bumped.
///
/// Dropping the pair is safe: the state machine only walks the pre-states a
/// program declares, so an omitted account is excluded from the diff and left
/// untouched.
///
/// Verbatim port of the SPEL macro's filter; see the bonding-curve copy for the
/// full rationale.
#[must_use]
pub fn filter_output(
    pre_states: Vec<AccountWithMetadata>,
    post_states: Vec<AccountPostState>,
) -> (Vec<AccountWithMetadata>, Vec<AccountPostState>) {
    pre_states
        .into_iter()
        .zip(post_states)
        .filter(|(pre, post)| {
            let is_default_owner = pre.account.program_owner == DEFAULT_PROGRAM_ID;
            let pre_is_default = pre.account == Account::default();
            let has_claim = post.required_claim().is_some();
            !is_default_owner || pre_is_default || has_claim
        })
        .unzip()
}

/// SECURITY: pin the clock slot to the canonical `CLOCK_01`. The submitter
/// chooses non-signer account ids, so without this an attacker could substitute
/// a non-decoding account, force the time to 0, and buy after the sale's
/// `t_end_ms` (priced at the opening weight). Mirrors the ldex AMM.
fn assert_clock(clock: &AccountWithMetadata) {
    assert_eq!(
        clock.account_id,
        lbp_core::CLOCK_01,
        "clock account must be the canonical CLOCK_01"
    );
}

/// On-chain ms timestamp from the threaded Clock account; 0 if it fails to
/// decode.
#[must_use]
pub fn clock_ms(clock: &AccountWithMetadata) -> i64 {
    assert_clock(clock);
    <lbp_core::ClockData as borsh::BorshDeserialize>::try_from_slice(clock.account.data.as_ref())
        .map(|c| c.timestamp)
        .unwrap_or(0)
}

/// Block id from the threaded Clock account, used for the per-block token
/// ceiling; 0 if it fails to decode.
#[must_use]
pub fn clock_block_id(clock: &AccountWithMetadata) -> u64 {
    assert_clock(clock);
    <lbp_core::ClockData as borsh::BorshDeserialize>::try_from_slice(clock.account.data.as_ref())
        .map(|c| c.block_id)
        .unwrap_or(0)
}

/// Echo the read-only Clock account back unchanged so `post_states.len()` equals
/// the account count on both the public and privacy paths (the LEZ privacy
/// circuit asserts a 1:1 account<->state mapping).
#[must_use]
pub fn echo_clock(
    mut post_states: Vec<AccountPostState>,
    clock: AccountWithMetadata,
) -> Vec<AccountPostState> {
    post_states.push(AccountPostState::new(clock.account));
    post_states
}
