//! Guest-entrypoint plumbing shared by every instruction in `src/main.rs`.
//!
//! Under LEZ v0.2.0-rc4 this was generated by SPEL's `#[lez_program]` macro. The
//! macro is gone in v0.2.1 (programs hand-write their dispatch), so the pieces it
//! silently supplied live here instead.

use lee_core::{
    account::{Account, AccountWithMetadata},
    program::{AccountPostState, DEFAULT_PROGRAM_ID},
};

/// Drops `(pre, post)` pairs that the state machine would reject.
///
/// `validate_execution` rule 7 fails any post-state whose `program_owner` is
/// `DEFAULT_PROGRAM_ID` when the matching pre-state was not a default account,
/// and rule 4 forbids changing `program_owner`. That is exactly the shape of a
/// **signer identity account**: lpad's handlers list the creator/owner among the
/// accounts they touch and echo it back unchanged, but a signer whose nonce has
/// already been bumped is non-default and program-owner-less, so emitting it is
/// fatal.
///
/// Dropping the pair is safe and is what SPEL did: the state machine only walks
/// the pre-states a program declares, so an omitted account is simply excluded
/// from the diff and left untouched.
///
/// Kept pairs are those that are either owned by some program, or still default
/// (an init, whose pre-state legitimately *is* default), or explicitly claimed.
///
/// This is a verbatim port of the SPEL macro's filter. Removing it makes every
/// instruction that lists a signer - `create_sale`, `close_sale`, `withdraw` -
/// fail with `NonDefaultAccountWithDefaultOwner`.
#[must_use]
pub fn filter_output(
    pre_states: Vec<AccountWithMetadata>,
    post_states: Vec<AccountPostState>,
) -> (Vec<AccountWithMetadata>, Vec<AccountPostState>) {
    pre_states
        .into_iter()
        .zip(post_states)
        .filter(|(pre, post)| {
            let is_default_owner = pre.account.program_owner == DEFAULT_PROGRAM_ID;
            let pre_is_default = pre.account == Account::default();
            let has_claim = post.required_claim().is_some();
            !is_default_owner || pre_is_default || has_claim
        })
        .unzip()
}

/// On-chain ms timestamp from the threaded Clock account; 0 if absent/invalid,
/// in which case the end-timestamp guard never trips and analytics ts is 0.
///
/// SECURITY: the submitter chooses every non-signer account id, so the clock
/// slot must be pinned to the canonical `CLOCK_01` - otherwise an attacker
/// could substitute a non-decoding account, force the timestamp to 0, and
/// bypass the sale's `end_timestamp_ms` close guard (buy after close at the
/// cheap pre-close price). Mirrors the ldex AMM clock authentication.
#[must_use]
pub fn clock_ms(clock: &AccountWithMetadata) -> i64 {
    assert_eq!(
        clock.account_id,
        bonding_curve_core::CLOCK_01,
        "clock account must be the canonical CLOCK_01"
    );
    <bonding_curve_core::ClockData as borsh::BorshDeserialize>::try_from_slice(
        clock.account.data.as_ref(),
    )
    .map(|c| c.timestamp)
    .unwrap_or(0)
}

/// Echo the read-only Clock account back unchanged so `post_states.len()` equals
/// the account count on both the public and privacy paths (the LEZ privacy
/// circuit asserts a 1:1 account<->state mapping).
#[must_use]
pub fn echo_clock(
    mut post_states: Vec<AccountPostState>,
    clock: AccountWithMetadata,
) -> Vec<AccountPostState> {
    post_states.push(AccountPostState::new(clock.account));
    post_states
}
