#!/usr/bin/env bash
# Install the `lpad` CLI so it runs as a command from any directory.
#
# What it does:
#   1. builds cli/target/release/lpad (incremental; skipped if up to date)
#   2. installs a small `lpad` launcher onto your PATH that points the binary at
#      the repo's guest ELFs + the risc0 toolchain + the proving circuits, so the
#      online/private/`program-id` commands work regardless of your current dir
#
# Usage:
#   bash scripts/install-cli.sh                 # install to ~/.local/bin
#   LPAD_INSTALL_DIR=~/bin bash scripts/install-cli.sh
#   bash scripts/install-cli.sh --rebuild       # force a clean rebuild
#   bash scripts/install-cli.sh --build-guests  # also (re)build the guest ELFs
#   bash scripts/install-cli.sh --add-path      # append the PATH line to your shell rc
set -euo pipefail
export PATH="$HOME/.cargo/bin:$HOME/.risc0/bin:$PATH"

REPO="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")/.." && pwd)"
BIN_DIR="${LPAD_INSTALL_DIR:-$HOME/.local/bin}"
BINARY="$REPO/cli/target/release/lpad"
BC_ELF="$REPO/programs/target/riscv-guest/bonding_curve-methods/bonding_curve-guest/riscv32im-risc0-zkvm-elf/release/bonding_curve.bin"
LBP_ELF="$REPO/programs/target/riscv-guest/lbp-methods/lbp-guest/riscv32im-risc0-zkvm-elf/release/lbp.bin"
WLEZ_ELF="$REPO/programs/target/riscv-guest/wlez-methods/wlez-guest/riscv32im-risc0-zkvm-elf/release/wlez.bin"
ATA_ELF="$REPO/programs/target/riscv-guest/ata-methods/ata-guest/riscv32im-risc0-zkvm-elf/release/ata.bin"
CIRCUITS="${LOGOS_BLOCKCHAIN_CIRCUITS:-$HOME/.logos-blockchain-circuits}"

REBUILD=0; BUILD_GUESTS=0; ADD_PATH=0
for a in "$@"; do case "$a" in
  --rebuild) REBUILD=1;; --build-guests) BUILD_GUESTS=1;; --add-path) ADD_PATH=1;;
  *) echo "unknown arg: $a" >&2; exit 2;; esac; done

command -v cargo >/dev/null || { echo "cargo not found - install Rust (https://rustup.rs) first" >&2; exit 1; }

# --- 1. guests (only if asked or missing; they are slow to build) -------------
if [ "$BUILD_GUESTS" = 1 ] || [ ! -f "$BC_ELF" ] || [ ! -f "$LBP_ELF" ] || [ ! -f "$WLEZ_ELF" ] || [ ! -f "$ATA_ELF" ]; then
  if [ "$BUILD_GUESTS" = 1 ]; then
    echo ">> building guest ELFs (this takes a few minutes)…"
    ( cd "$REPO/programs" && cargo build --release \
        -p bonding_curve-methods -p lbp-methods -p wlez-methods -p ata-methods )
  else
    echo "!! some guest ELFs not found - offline + public commands still work, but"
    echo "   'program-id', 'buy-private', wrap/shield-lez (wlez), and the ATA commands"
    echo "   need them. Build with: bash scripts/install-cli.sh --build-guests"
  fi
fi

# --- 2. build the CLI binary --------------------------------------------------
[ "$REBUILD" = 1 ] && rm -f "$BINARY"
if [ ! -x "$BINARY" ] || [ "$REBUILD" = 1 ]; then
  echo ">> building lpad (release)…"
  ( cd "$REPO/cli" && RISC0_SKIP_BUILD=1 cargo build --release --bin lpad )
else
  echo ">> lpad already built ($BINARY) - use --rebuild to force"
fi
[ -x "$BINARY" ] || { echo "build failed: $BINARY missing" >&2; exit 1; }

# --- 3. install the launcher --------------------------------------------------
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/lpad" <<EOF
#!/usr/bin/env bash
# lpad launcher - generated by scripts/install-cli.sh ($REPO)
export PATH="\$HOME/.cargo/bin:\$HOME/.risc0/bin:\$PATH"
: "\${LOGOS_BLOCKCHAIN_CIRCUITS:=$CIRCUITS}"; export LOGOS_BLOCKCHAIN_CIRCUITS
: "\${LPAD_BC_ELF:=$BC_ELF}";     export LPAD_BC_ELF
: "\${LPAD_LBP_ELF:=$LBP_ELF}";   export LPAD_LBP_ELF
: "\${LPAD_WLEZ_ELF:=$WLEZ_ELF}"; export LPAD_WLEZ_ELF
: "\${LPAD_ATA_ELF:=$ATA_ELF}";   export LPAD_ATA_ELF
exec "$BINARY" "\$@"
EOF
chmod +x "$BIN_DIR/lpad"
echo ">> installed launcher: $BIN_DIR/lpad -> $BINARY"

# --- 4. PATH check ------------------------------------------------------------
case ":$PATH:" in
  *":$BIN_DIR:"*) ON_PATH=1;;
  *) ON_PATH=0;;
esac
if [ "$ON_PATH" = 0 ]; then
  RC="$HOME/.bashrc"; [ -n "${ZSH_VERSION:-}" ] && RC="$HOME/.zshrc"
  LINE="export PATH=\"$BIN_DIR:\$PATH\""
  if [ "$ADD_PATH" = 1 ]; then
    echo "$LINE" >> "$RC"; echo ">> added to $RC - run: source $RC"
  else
    echo "!! $BIN_DIR is not on your PATH. Add it:"
    echo "     echo '$LINE' >> $RC && source $RC"
    echo "   (or re-run with --add-path)"
  fi
fi

# --- 5. verify ----------------------------------------------------------------
echo ">> verifying:"
"$BIN_DIR/lpad" bc quote --vt 2000000 --vc 50000 --fee-bps 100 --in 1000 | sed 's/^/     /'
echo
echo "Done. Try:  lpad --help    |    lpad bc quote --vt 2000000 --vc 50000 --in 1000"
echo "Online commands need a wallet + sequencer - source an env from scripts/bootstrap.sh first."
