#!/usr/bin/env bash
# Install the `lpad` CLI so it runs as a command from any directory.
#
# What it does:
#   1. builds cli/target/release/lpad (incremental; skipped if up to date)
#   2. installs a small `lpad` launcher onto your PATH
#
# Since the LEZ v0.2.1 upgrade the launcher is nearly trivial: the guest ELFs are
# compiled into the binary from the committed reproducible artifacts, so there are
# no LPAD_*_ELF paths to point at (previously a guest rebuild could silently leave
# the CLI submitting against an undeployed image id). The proving circuits are
# likewise no longer a separate download, so LOGOS_BLOCKCHAIN_CIRCUITS is gone.
#
# Usage:
#   bash scripts/install-cli.sh                 # install to ~/.local/bin
#   LPAD_INSTALL_DIR=~/bin bash scripts/install-cli.sh
#   bash scripts/install-cli.sh --rebuild       # force a clean rebuild
#   bash scripts/install-cli.sh --add-path      # append the PATH line to your shell rc
set -euo pipefail
export PATH="$HOME/.cargo/bin:$HOME/.risc0/bin:$PATH"

REPO="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")/.." && pwd)"
BIN_DIR="${LPAD_INSTALL_DIR:-$HOME/.local/bin}"
BINARY="$REPO/cli/target/release/lpad"
ARTIFACTS="$REPO/programs/artifacts/lpad"

REBUILD=0; ADD_PATH=0
for a in "$@"; do case "$a" in
  --rebuild) REBUILD=1;; --add-path) ADD_PATH=1;;
  # Accepted for backwards compatibility; guests now come from committed
  # artifacts and are built by their own script.
  --build-guests) echo "!! --build-guests is obsolete; run: bash scripts/build-guests.sh" >&2;;
  *) echo "unknown arg: $a" >&2; exit 2;; esac; done

command -v cargo >/dev/null || { echo "cargo not found - install Rust (https://rustup.rs) first" >&2; exit 1; }

# --- 1. the committed guest artifacts the binary embeds -----------------------
for g in bonding_curve lbp wlez; do
  [ -f "$ARTIFACTS/$g.bin" ] || {
    echo "!! missing $ARTIFACTS/$g.bin" >&2
    echo "   These are committed to the repo; if you changed guest code, rebuild with:" >&2
    echo "     bash scripts/build-guests.sh" >&2
    exit 1
  }
done

# --- 2. build the CLI binary --------------------------------------------------
[ "$REBUILD" = 1 ] && rm -f "$BINARY"
if [ ! -x "$BINARY" ] || [ "$REBUILD" = 1 ]; then
  echo ">> building lpad (release)…"
  ( cd "$REPO/cli" && RISC0_SKIP_BUILD=1 cargo build --release --bin lpad )
else
  echo ">> lpad already built ($BINARY) - use --rebuild to force"
fi
[ -x "$BINARY" ] || { echo "build failed: $BINARY missing" >&2; exit 1; }

# --- 3. install the launcher --------------------------------------------------
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/lpad" <<EOF
#!/usr/bin/env bash
# lpad launcher - generated by scripts/install-cli.sh ($REPO)
export PATH="\$HOME/.cargo/bin:\$HOME/.risc0/bin:\$PATH"
exec "$BINARY" "\$@"
EOF
chmod +x "$BIN_DIR/lpad"
echo ">> installed launcher: $BIN_DIR/lpad -> $BINARY"

# --- 4. PATH check ------------------------------------------------------------
case ":$PATH:" in
  *":$BIN_DIR:"*) ON_PATH=1;;
  *) ON_PATH=0;;
esac
if [ "$ON_PATH" = 0 ]; then
  RC="$HOME/.bashrc"; [ -n "${ZSH_VERSION:-}" ] && RC="$HOME/.zshrc"
  LINE="export PATH=\"$BIN_DIR:\$PATH\""
  if [ "$ADD_PATH" = 1 ]; then
    echo "$LINE" >> "$RC"; echo ">> added to $RC - run: source $RC"
  else
    echo "!! $BIN_DIR is not on your PATH. Add it:"
    echo "     echo '$LINE' >> $RC && source $RC"
    echo "   (or re-run with --add-path)"
  fi
fi

# --- 5. verify ----------------------------------------------------------------
echo ">> verifying:"
"$BIN_DIR/lpad" bc quote --vt 2000000 --vc 50000 --fee-bps 100 --in 1000 | sed 's/^/     /'
echo
echo "Done. Try:  lpad --help    |    lpad bc quote --vt 2000000 --vc 50000 --in 1000"
echo "Online commands need a wallet + sequencer - source an env from scripts/bootstrap.sh first."
